services:
  app:
    build:
      context: .
      platforms:
        - linux/amd64
    ports:
      - "5001:8080"
    depends_on:
      db:
        condition: service_healthy # Espera a que la BD esté 100% lista
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/blacklist_db

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blacklist_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d blacklist_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
