name: Pruebas unitarias

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    working-directory: blacklist_app

jobs:
  job1:
    name: Pruebas y cobertura
    runs-on: ubuntu-latest
    steps:
      - name: Checkout de repositorio
        uses: actions/checkout@v4

      - name: Configuración de entorno de Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar Poetry
        run: pip install poetry

      - name: Instalar dependencias
        run: poetry install --no-interaction

      - name: Correr pruebas con cobertura
        id: correr-pruebas
        run: poetry run pytest --cov=src --cov-report=term-missing
